services:
  mysql:
    image: mysql:8.0
    container_name: eastern-firefighter-mysql
    environment:
      MYSQL_ROOT_PASSWORD: swj21bsss
      MYSQL_DATABASE: e-fire
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Eastern-Firefighter/EF-webapp/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: eastern-firefighter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: eastern-firefighter-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  mysql_data:
  redis_data:
  ollama_data: